// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzznVuvl3eypHVbuSHCX0l1fAU4RIbZuo',
    appId: '1:388312551536:web:1b5ba92e5547c0719de4b5',
    messagingSenderId: '388312551536',
    projectId: 'japanese-review',
    authDomain: 'japanese-review.firebaseapp.com',
    storageBucket: 'japanese-review.appspot.com',
    measurementId: 'G-SWLM98N40S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKxDffd-eNjWS9J5PtUz1_KYWjhC8kiq0',
    appId: '1:388312551536:android:f84f2c0c5a81d5789de4b5',
    messagingSenderId: '388312551536',
    projectId: 'japanese-review',
    storageBucket: 'japanese-review.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuJBKElfsBZB8YxBNdtmnFr6namFKKMA',
    appId: '1:388312551536:ios:0c219a41562e11059de4b5',
    messagingSenderId: '388312551536',
    projectId: 'japanese-review',
    storageBucket: 'japanese-review.appspot.com',
    iosClientId: '388312551536-uvqfbbh7vb38brdc5aqqtlkfit8m85oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.language',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYuJBKElfsBZB8YxBNdtmnFr6namFKKMA',
    appId: '1:388312551536:ios:0c219a41562e11059de4b5',
    messagingSenderId: '388312551536',
    projectId: 'japanese-review',
    storageBucket: 'japanese-review.appspot.com',
    iosClientId: '388312551536-uvqfbbh7vb38brdc5aqqtlkfit8m85oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.language',
  );
}
